### ISSUE TITLE
docker部署和运行sentry

### ISSUE THREAD

**Issue by timest** [timest/blog#2]
## 部署与运行
clone[github](https://github.com/getsentry/onpremise.git)上的项目，里面的compose文件

```git
git clone https://github.com/getsentry/onpremise.git
```

dc部署和运行看[Readme](https://github.com/getsentry/onpremise/blob/master/README.md#up-and-running)就可以，主要4个步骤：
1. mkdir -p data/{sentry, postgres}
2. docker-compose run --rm web config generate-secret-key  [嫌麻烦就自己随便写一串随机字符，但不建议这么做]
3. docker-compose run --rm web upgrade 。这一步是migrate数据，因为postgre数据在文件夹data/postgres，所以后期随意up/stop/rm/rmi 都不会对数据有影响
4. docker-compose up -d

完成，访问http://localhost:9000 可以看到sentry 。

## 部署在nginx上
按主流方式来就可以，有问题留言。这里值得注意的是docker的网络，一般项目会有两种需求：
1. sentry和python/node等项目放在一个compose或network里，这是最简单的需求，也就是什么都不用改，加个Link, nginx配置里直接可以访问sentry web的ip和9000端口
2. sentry单独作为一个compose，就需要稍微做些调整里,看下面这个compose:

```yml
version: '2'
services:
  base:
    build: .
    environment:
      # SENTRY_SECRET_KEY: 'random_string'
      SENTRY_MEMCACHED_HOST: memcached
      SENTRY_REDIS_HOST: redis
      SENTRY_POSTGRES_HOST: postgres
    volumes:
      - ./data/sentry:/var/lib/sentry/files
    networks:
      - sentry

  smtp:
    image: tianon/exim4
    networks:
      - sentry

  memcached:
    image: memcached:1.4
    networks:
      - sentry

  redis:
    image: redis:3.2-alpine
    networks:
      - sentry

  postgres:
    image: postgres:9.5
    networks:
      - sentry
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  web:
    extends: base
    networks:
      - sentry
    links:
      - redis
      - postgres
      - memcached
      - smtp
    ports:
      - '9000:9000'

  cron:
    extends: base
    command: run cron
    networks:
      - sentry
    links:
      - redis
      - postgres
      - memcached
      - smtp

  worker:
    extends: base
    networks:
      - sentry
    command: run worker
    links:
      - redis
      - postgres
      - memcached
      - smtp

networks:
    sentry:
        external: true
```
注意到最后的networks和每个组里的networks了吗？目的是将sentry加入到一个叫sentry的网络里，这个网络必须已经存在的，如果没有，就通过下面这命令create一个。
```docker
docker network create --drvier=bridge sentry 
```
然后在配置nginx的compose里也加上：

```yml
networks:
 - sentry 
```

这样做的目的，就是让nginx可以访问到sentry web的ip和端口，就可以按照正常的方式去配置nginx了。

## sentry 配置mail server
在clone下来的目录里，有个config.yml，在里面进行配置就可以:

```yml
mail.backend: 'smtp'  
mail.host: 'smtp.exmail.qq.com'
mail.port: 587
mail.username: 'sentry@example.com'
mail.password: 'example'
mail.use-tls: true
# The email address to send on behalf of
mail.from: 'sentry@example.com'
```

这里用国内腾讯企业邮箱做个demo说两点，可能为你节约不少时间：
1. **端口。** 在腾讯企业邮箱的设置相关页面，会告诉你SMTP的端口是**465**，可能你平时用python等一些语言写email脚本也是用的465，但sentry只支持tls而非ssh，所以端口改587试试。
2. **mail.from必须要和mail.username一样。** 这个可能看客户端，腾讯企业邮箱是必须一致才行。
